# Generated by Django 3.2.8 on 2021-10-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Krypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('information', models.CharField(max_length=250)),
                ('symbol', models.CharField(max_length=50)),
            ],
        ),
    ]
