# Generated by Django 3.2.8 on 2021-10-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211030_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Krypto',
        ),
    ]
