# Generated by Django 3.2.8 on 2021-11-02 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
