# Generated by Django 3.2.8 on 2021-11-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20211102_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
