# Generated by Django 3.2.8 on 2021-11-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
